### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by hexahigh** [RestoreMonarchy/UnturnedMapMergeTool#2]
I might just be stupid but i can't figure out how to use this program. When i run it i get an error that says:
```
[18:52:11 INF] UnturnedMapMergeTool v0.2.0.0 has been loaded!
[18:52:11 INF] Start combining 2 maps
[18:52:11 ERR]
System.NullReferenceException: Object reference not set to an instance of an object.
   at UnturnedMapMergeTool.DataMergeTools.ObjectsDataMergeTool.ReadData(CopyMap copyMap)
   at Program.Start(Config config)
   at Program.Main(String[] args)
[18:52:11 INF] Press any key to exit the program..
``` 
Im guessing that i need to give the program an argument that says where the maps are located but i can't figure out how to do that.

Looking forward to your reply.

**Comment by hexahigh** [comment]
I ran the program again and it game me some config files. Im just wondering what the ShiftX and ShiftY options are

**Comment by hexahigh** [comment]
nvm i figured it out. great tool btw

**Comment by hexahigh** [comment]
i still need help with the ShiftX and ShiftY options
